# Generated by Django 4.2.1 on 2023-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=12, upload_to='media/'),
            preserve_default=False,
        ),
    ]
