# Generated by Django 4.2.1 on 2023-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='fibre',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='protein',
            field=models.IntegerField(null=True),
        ),
    ]
