# Generated by Django 4.2.1 on 2023-07-18 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='carbs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='energy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fibre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='protein',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
