# Generated by Django 4.2.1 on 2023-07-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
