# Generated by Django 4.2.1 on 2023-08-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_cartitem_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='processed',
        ),
    ]
