# Generated by Django 4.2.1 on 2023-08-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_cartitem_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
